kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: marketing-demo-environment-fe
rules:
  - apiGroups: [""]
    resources: ["configmaps", "pods", "services", "endpoints", "secrets"]
    verbs: ["get", "list", "watch"]