kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: marketing-demo-environment-fe
subjects:
  - kind: ServiceAccount
    name: marketing-demo-environment-fe
roleRef:
  kind: Role
  name: marketing-demo-environment-fe
  apiGroup: rbac.authorization.k8s.io